# Generated by Django 5.0.3 on 2024-08-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('pm25', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('co', models.IntegerField()),
                ('ozone', models.IntegerField()),
                ('no2', models.IntegerField()),
            ],
        ),
    ]
