# Generated by Django 5.0.3 on 2024-08-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration1',
            new_name='aqi_index',
        ),
    ]
