# Generated by Django 5.0.3 on 2024-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0006_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
