# Generated by Django 5.0.3 on 2024-12-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0009_airqualitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.CharField(choices=[('0-12', '0-12 years'), ('13-18', '13-18 years'), ('19-40', '19-40 years'), ('41-60', '41-60 years'), ('61+', '61 years and above')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('respiratory', models.CharField(choices=[('asthma', 'Asthma'), ('copd', 'COPD'), ('chronic_bronchitis', 'Chronic Bronchitis'), ('emphysema', 'Emphysema'), ('none', 'None of the above')], max_length=30)),
                ('smoking_history', models.CharField(choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('current', 'Current smoker'), ('passive', 'Exposed to secondhand smoke')], max_length=10)),
                ('environment', models.CharField(choices=[('urban', 'Urban area with heavy traffic'), ('industrial', 'Near industrial zone'), ('rural', 'Rural area'), ('coastal', 'Coastal area')], max_length=30)),
                ('occupation', models.CharField(choices=[('construction', 'Construction/Mining'), ('chemical', 'Chemical Industry'), ('healthcare', 'Healthcare'), ('agriculture', 'Agriculture'), ('office', 'Office Environment'), ('other', 'Other')], max_length=20)),
                ('symptom', models.CharField(choices=[('cough', 'Frequent coughing'), ('breathlessness', 'Shortness of breath'), ('wheezing', 'Wheezing'), ('chest_pain', 'Chest tightness'), ('other', 'Prefer not to say')], max_length=30)),
                ('exposure_type', models.CharField(choices=[('construction_mining', 'Construction/Mining'), ('chemical_industry', 'Chemical Industry'), ('healthcare', 'Healthcare'), ('agriculture', 'Agriculture'), ('office_environment', 'Office Environment'), ('other', 'Other')], max_length=50)),
                ('medical_condition', models.CharField(choices=[('hypertension', 'Hypertension'), ('diabetes', 'Diabetes'), ('heart_disease', 'Heart Disease'), ('allergies', 'Allergies'), ('immunocompromised', 'Immunocompromised')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_pollution.user')),
            ],
        ),
    ]
