# Generated by Django 5.0.3 on 2024-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0010_healthassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthassessment',
            name='created_at',
        ),
    ]
