# Generated by Django 5.0.3 on 2024-12-16 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0011_remove_healthassessment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthassessment',
            name='exposure_type',
        ),
        migrations.AddField(
            model_name='healthassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='age_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='environment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='medical_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='respiratory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='smoking_history',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='symptom',
            field=models.TextField(blank=True),
        ),
    ]
