# Generated by Django 5.0.3 on 2024-12-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0013_rename_occupation_healthassessment_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthassessment',
            old_name='username',
            new_name='sername',
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='age_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='common_symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='living_environment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='medical_history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='occupational_exposure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='respiratory_conditions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthassessment',
            name='smoking_history',
            field=models.CharField(max_length=50),
        ),
    ]
