# Generated by Django 5.0.3 on 2024-12-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0014_rename_username_healthassessment_sername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthassessment',
            old_name='sername',
            new_name='username',
        ),
    ]
