# Generated by Django 5.0.3 on 2024-12-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0017_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
