# Generated by Django 5.0.3 on 2025-01-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_pollution', '0018_remove_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthassessment',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
    ]
